name: spider-animation
version: '${project.version}'
main: com.heledron.spideranimation.SpiderAnimationPlugin
api-version: '1.20'

commands:
  gait:
    description: Set gait options
    usage: /gait <option:string> <value:double>
  fall:
    description: Teleport the spider up by the specified height
    usage: /fall <height:double>
  debug:
    description: Toggle debug options
    usage: /debug <option:string> <value:boolean?>